[package]
name = "dogoap_macros"
version = "0.2.0"
edition = "2021"
description = "dogoap_macros"
license = "MIT"
homepage = "https://github.com/victorb/dogoap"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
